import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as readline from 'readline';

export interface GCodeMetadata {
    printTimeSeconds: number;
    filamentWeightGrams: number;
    filamentLengthMm: number;
    layerHeightMm?: number;
    infillDensity?: number;
    nozzleTemp?: number;
    bedTemp?: number;
    hasSupports: boolean;
    slicer?: string;
}

@Injectable()
export class GCodeParserService {
    private readonly logger = new Logger(GCodeParserService.name);

    async parseFile(filePath: string): Promise<GCodeMetadata> {
        const fileStream = fs.createReadStream(filePath);
        const rl = readline.createInterface({
            input: fileStream,
            crlfDelay: Infinity,
        });

        const metadata: GCodeMetadata = {
            printTimeSeconds: 0,
            filamentWeightGrams: 0,
            filamentLengthMm: 0,
            hasSupports: false,
        };

        for await (const line of rl) {
            this.parseLine(line, metadata);
        }

        return metadata;
    }

    private parseLine(line: string, metadata: GCodeMetadata) {
        // Common slicer comments (Cura, Prusa, Orca, Bambu)

        // Time estimation
        if (line.includes('TIME:') || line.includes('estimated printing time (normal mode) =')) {
            const timeMatch = line.match(/TIME:(\d+)/) || line.match(/estimated printing time \(normal mode\) = (.*)/);
            if (timeMatch) {
                if (line.includes('TIME:')) {
                    metadata.printTimeSeconds = parseInt(timeMatch[1]);
                } else {
                    metadata.printTimeSeconds = this.convertPrusaTimeToSeconds(timeMatch[1]);
                }
            }
        }

        // Filament usage
        if (line.includes('Filament used:') || line.includes('filament used [g] =') || line.includes('filament used [mm] =')) {
            const weightMatch = line.match(/filament used \[g\] = ([\d.]+)/);
            const lengthMatch = line.match(/filament used \[mm\] = ([\d.]+)/);

            if (weightMatch) metadata.filamentWeightGrams = parseFloat(weightMatch[1]);
            if (lengthMatch) metadata.filamentLengthMm = parseFloat(lengthMatch[1]);
        }

        // Supports
        if (line.includes('support_material = 1') || line.includes('support_enable = 1') || line.includes(';LAYER_CHANGE')) {
            if (line.includes('support') && (line.includes('1') || line.includes('true'))) {
                metadata.hasSupports = true;
            }
        }

        // Slicer ID
        if (line.includes('generated by')) {
            if (line.includes('Cura')) metadata.slicer = 'Cura';
            if (line.includes('PrusaSlicer')) metadata.slicer = 'Prusa';
            if (line.includes('OrcaSlicer')) metadata.slicer = 'Orca';
            if (line.includes('Bambu Studio')) metadata.slicer = 'Bambu';
        }
    }

    private convertPrusaTimeToSeconds(timeStr: string): number {
        // Format: 1h 20m 30s
        let total = 0;
        const h = timeStr.match(/(\d+)h/);
        const m = timeStr.match(/(\d+)m/);
        const s = timeStr.match(/(\d+)s/);

        if (h) total += parseInt(h[1]) * 3600;
        if (m) total += parseInt(m[1]) * 60;
        if (s) total += parseInt(s[1]);

        return total;
    }
}
